### ISSUE TITLE
Delete profile or group flows

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#146] opened 2019-01-28 21:48 UTC
# Problem
- In order to respect GDPR we need the ability for users to remove all data we have stored on them

# Solution
Add flows for deleting profiles & groups including email confirmations etc

**Comment by Manoj-nathwani** [comment] 2019-01-30 12:14
Done here https://github.com/rtcharity/hubreboot/commit/9770f7a1ce749c0bc62de26f630a7c377e164610

**Comment by Manoj-nathwani** [comment] 2019-01-30 12:16
@sebgrebe can you add it to the front-end please 🙏 
You can access the URL via `{% url 'delete_profile' %}`

**Comment by sebgrebe** [comment] 2019-02-02 16:33
@Manoj-nathwani Done.

**Comment by Manoj-nathwani** [comment] 2019-02-05 07:35
Yes i'll deff do it BEFORE launch

**Comment by Manoj-nathwani** [comment] 2019-02-05 07:36
Thanks for sorting out the front-end :)

**Comment by taymonbeal** [comment] 2019-02-21 19:14
Duplicate of #304

**Closed** 2019-02-21 19:15 UTC
