### ISSUE TITLE
Password reset doesn't work

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#257] opened 2019-02-16 02:23 UTC
![image](https://user-images.githubusercontent.com/14195560/52893205-cee78400-314e-11e9-8a53-6f8db3b300de.png)

Used: https://staging.eahub.org/profile/password_reset/

**Comment by Manoj-nathwani** [comment] 2019-02-16 08:22
- I managed to run through the entire reset-password process successfully on https://eahub.azurewebsites.net without any issues
- This means it's an issue with how staging is configured with our sendgrid account. It's likely not whitelisted as a domain or something.
- I'm going to close this as I don't feel it's worth looking into anytime soon

**Comment by sebgrebe** [comment] 2019-02-16 11:16
I believe this happens when someone enters an email that's not registered. It's working for an email I'm registered with, but I'm also getting that 500 error when entering an email that is not registered.
The error is (you can see that on DEBUG=True):
```
type "citext" does not exist
LINE 1: ...profile" WHERE (UPPER("profiles_profile"."email"::citext) = ..
```
We should rather have a "Sorry, we couldn't find your email" message.
No pre-launch priority in my mind, though.

**Comment by piotr-asdf** [comment] 2019-02-20 22:59
Right now I'm getting:
"Bad request
We can't handle this request. If you weren't doing anything unusual, contact our Tech team."
When trying to reset password, additionally, Thunderbird thinks it's a suspicious link 😛

**Comment by taymonbeal** [comment] 2019-02-20 23:34
Is this happening consistently? I can't repro it.

**Comment by piotr-asdf** [comment] 2019-02-20 23:44
I can't reproduce it anymore either, now I was able to successfully reset my password.

**Closed** 2019-02-20 23:53 UTC
Labels: fix before launch
