### ISSUE TITLE
Allow users to edit group organisers

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#83] opened 2019-01-08 16:19 UTC

**Comment by michaltrzesimiech** [comment] 2019-02-15 23:07
Removing donations from title.

**Comment by michaltrzesimiech** [comment] 2019-02-15 23:08
@Richenda should we prioritize this prior to the launch on Monday?

**Comment by sebgrebe** [comment] 2019-02-15 23:21
@michaltrzesimiech donations have been removed from group profiles.

**Comment by michaltrzesimiech** [comment] 2019-02-15 23:23
@sebgrebe I meant this part: 

> Allow users to edit group organisers

**Comment by sebgrebe** [comment] 2019-02-15 23:24
> @sebgrebe I meant this part:
> 
> > Allow users to edit group organisers

Ah ok, I see.

**Comment by Richenda** [comment] 2019-02-15 23:53
> @Richenda should we prioritize this prior to the launch on Monday?

If it's doable.

**Comment by Manoj-nathwani** [comment] 2019-02-16 12:20
Doesn't look feasible to do within 48hrs, but straight after yes, it's the next major feature i'll be working on.

**Comment by Richenda** [comment] 2019-02-16 22:28
Ok no worries!

**Comment by taymonbeal** [comment] 2019-02-21 19:07
Duplicate of #304.

**Closed by taymonbeal** 2019-02-21 19:07 UTC
